const express = require('express');
const Groq = require('groq-sdk');
const authenticateToken = require('../middleware/auth');

const router = express.Router();

// Initialize Groq SDK
const GROQ_API_KEY = process.env.GROQ_API_KEY;
let groq = null;

if (GROQ_API_KEY) {
    groq = new Groq({ apiKey: GROQ_API_KEY });
}

/* ─── POST /api/ai/refine ─── */
router.post('/refine', authenticateToken, async (req, res) => {
    try {
        const { content, instruction } = req.body;

        if (!content) {
            return res.status(400).json({ error: 'Content is required for AI refinement.' });
        }

        if (!GROQ_API_KEY || !groq) {
            return res.status(503).json({ 
                error: 'Groq AI Service is not configured. Please set the GROQ_API_KEY environment variable.' 
            });
        }

        const prompt = `You are an expert co-author and editor for a creative writing platform. 
Your task is to refine, polish, and improve the provided story chapter content.

User's instruction for this edit: "${instruction || 'Polishing, fixing grammar, and improving flow and description.'}"

---
Original Content:
${content}
---

Provide only the improved version of the chapter content. Do not add any conversational intros, explanations, or outros. Your response must contain only the polished text.`;

        const completion = await groq.chat.completions.create({
            messages: [
                { role: 'user', content: prompt }
            ],
            model: 'llama3-8b-8192',
            temperature: 0.7,
        });

        const refinedContent = completion.choices[0]?.message?.content;

        if (!refinedContent) {
            return res.status(500).json({ error: 'No response generated by Groq AI.' });
        }

        res.json({ refinedContent: refinedContent.trim() });
    } catch (err) {
        console.error('Groq AI error:', err);
        res.status(500).json({ error: `AI refinement failed: ${err.message}` });
    }
});

module.exports = router;
