const express = require('express');
const Groq = require('groq-sdk');
const authenticateToken = require('../middleware/auth');

const router = express.Router();

// Initialize Groq SDK
const GROQ_API_KEY = process.env.GROQ_API_KEY;
let groq = null;

if (GROQ_API_KEY) {
    groq = new Groq({ apiKey: GROQ_API_KEY });
}

/* ─── POST /api/ai/refine ─── */
router.post('/refine', authenticateToken, async (req, res) => {
    try {
        const { content, instruction } = req.body;

        if (!content) {
            return res.status(400).json({ error: 'Content is required for AI mood analysis.' });
        }

        if (!GROQ_API_KEY || !groq) {
            return res.status(503).json({ 
                error: 'Groq AI Service is not configured. Please set the GROQ_API_KEY environment variable.' 
            });
        }

        const prompt = `You are an expert emotional analyzer and mental wellness guide for the 'Mood Mirror' application. 
Your task is to analyze the user's journal entry content, identify their emotional state, highlight key sentiments, and provide constructive, empathetic feedback and reflection (the 'mirror' effect).

User's specific instruction/focus for this analysis: "${instruction || 'Providing general mood reflection and emotional support.'}"

---
Journal Entry Content:
${content}
---

Provide an empathetic response with emotional analysis, key sentiment themes, and reflection. Keep it concise, helpful, and supportive.`;

        const completion = await groq.chat.completions.create({
            messages: [
                { role: 'user', content: prompt }
            ],
            model: 'llama-3.1-8b-instant',
            temperature: 0.7,
        });

        const refinedContent = completion.choices[0]?.message?.content;

        if (!refinedContent) {
            return res.status(500).json({ error: 'No response generated by Groq AI.' });
        }

        res.json({ refinedContent: refinedContent.trim() });
    } catch (err) {
        console.error('Groq AI error:', err);
        res.status(500).json({ error: `AI mood analysis failed: ${err.message}` });
    }
});

module.exports = router;
